import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type Language = 'uz' | 'ru' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    discover: 'Avtomobillarni toping',
    browse: "Bizning premium avtomobillar kolleksiyasini ko'ring.",
    searchPlaceholder: "Brend yoki model bo'yicha qidirish...",
    filters: 'Filtrlar',
    buyNow: 'Sotib olish',
    login: 'Kirish',
    register: "Ro'yxatdan o'tish",
    logout: 'Chiqish',
    adminDashboard: 'Admin paneli',
    mileage: 'Masofa',
    condition: 'Holat',
    year: 'Yili',
    cancel: 'Bekor qilish',
    confirmOrder: 'Buyurtma berish',
    orderSuccess: 'Buyurtma muvaffaqiyatli yaratildi!',
    noVehicles: "So'rovingiz bo'yicha avtomobil topilmadi.",
    welcomeBack: 'Xush kelibsiz',
    signInToContinue: 'Davom etish uchun tizimga kiring',
    emailLabel: 'Elektron pochta',
    passwordLabel: 'Parol',
    forgotPassword: 'Parolni unutdingizmi?',
    signInButton: 'Kirish',
    createAccount: 'Hisob yaratish',
    joinToday: "Bugun Drive.net'ga qo'shiling",
    fullName: "To'liq ism",
    selectPlan: "Bo'lib to'lash rejasini tanlang",
    payFull: "To'liq to'lash",
    noInterest: "Qo'shimcha foiz yo'q",
    months: 'oy',
    interest: 'Foiz',
    summary: "Umumiy ma'lumot",
    basePrice: 'Asosiy narx',
    total: 'Jami',
    monthlyPayment: "Oylik to'lov",
    pending: 'Kutilmoqda',
    confirmed: 'Tasdiqlangan',
    delivered: 'Yetkazilgan',
    cancelled: 'Bekor qilingan',
    orderId: 'Buyurtma ID',
    customer: 'Mijoz',
    vehicle: 'Avtomobil',
    date: 'Sana',
    amount: 'Summa',
    status: 'Holat',
    orders: 'Buyurtmalar',
    manageOrdersDesc: "Mijoz buyurtmalarini boshqaring.",
    orderStatusUpdated: 'yangilandi',
    confirmDelete: "O'chirishni tasdiqlaysizmi?",
    orderDeleted: "Buyurtma o'chirildi",
  },
  ru: {
    discover: 'Найдите автомобили',
    browse: 'Посмотрите нашу коллекцию премиальных автомобилей.',
    searchPlaceholder: 'Поиск по бренду или модели...',
    filters: 'Фильтры',
    buyNow: 'Купить',
    login: 'Войти',
    register: 'Регистрация',
    logout: 'Выйти',
    adminDashboard: 'Панель администратора',
    mileage: 'Пробег',
    condition: 'Состояние',
    year: 'Год',
    cancel: 'Отмена',
    confirmOrder: 'Оформить заказ',
    orderSuccess: 'Заказ успешно создан!',
    noVehicles: 'По вашему запросу ничего не найдено.',
    welcomeBack: 'С возвращением',
    signInToContinue: 'Войдите в аккаунт, чтобы продолжить',
    emailLabel: 'Электронная почта',
    passwordLabel: 'Пароль',
    forgotPassword: 'Забыли пароль?',
    signInButton: 'Войти',
    createAccount: 'Создать аккаунт',
    joinToday: 'Присоединяйтесь к Drive.net сегодня',
    fullName: 'Полное имя',
    selectPlan: 'Выберите план рассрочки',
    payFull: 'Оплатить полностью',
    noInterest: 'Без дополнительного процента',
    months: 'мес.',
    interest: 'Процент',
    summary: 'Сводка',
    basePrice: 'Базовая цена',
    total: 'Итого',
    monthlyPayment: 'Ежемесячный платеж',
    pending: 'В ожидании',
    confirmed: 'Подтверждено',
    delivered: 'Доставлено',
    cancelled: 'Отменено',
    orderId: 'ID заказа',
    customer: 'Клиент',
    vehicle: 'Автомобиль',
    date: 'Дата',
    amount: 'Сумма',
    status: 'Статус',
    orders: 'Заказы',
    manageOrdersDesc: 'Управляйте заказами клиентов.',
    orderStatusUpdated: 'обновлен',
    confirmDelete: 'Подтвердить удаление?',
    orderDeleted: 'Заказ удален',
  },
  en: {
    discover: 'Discover Vehicles',
    browse: 'Browse our exclusive collection of premium cars.',
    searchPlaceholder: 'Search by brand or model...',
    filters: 'Filters',
    buyNow: 'Buy Now',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    adminDashboard: 'Admin Dashboard',
    mileage: 'Mileage',
    condition: 'Condition',
    year: 'Year',
    cancel: 'Cancel',
    confirmOrder: 'Confirm Order',
    orderSuccess: 'Order placed successfully!',
    noVehicles: 'No vehicles found matching your criteria.',
    welcomeBack: 'Welcome Back',
    signInToContinue: 'Sign in to your account to continue',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    forgotPassword: 'Forgot password?',
    signInButton: 'Sign In',
    createAccount: 'Create Account',
    joinToday: 'Join Drive.net today',
    fullName: 'Full Name',
    selectPlan: 'Select Installment Plan',
    payFull: 'Pay in Full',
    noInterest: 'No extra interest',
    months: 'Months',
    interest: 'Interest',
    summary: 'Summary',
    basePrice: 'Base Price',
    total: 'Total',
    monthlyPayment: 'Monthly Payment',
    pending: 'Pending',
    confirmed: 'Confirmed',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    orderId: 'Order ID',
    customer: 'Customer',
    vehicle: 'Vehicle',
    date: 'Date',
    amount: 'Amount',
    status: 'Status',
    orders: 'Orders',
    manageOrdersDesc: 'Manage customer purchases.',
    orderStatusUpdated: 'updated',
    confirmDelete: 'Confirm delete?',
    orderDeleted: 'Order deleted',
  },
};

export const useLanguageStore = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'uz',
      setLanguage: (language) => set({ language }),
      t: (key) => translations[get().language][key] || key,
    }),
    {
      name: 'drive-language',
    },
  ),
);
